### ISSUE TITLE
Add django-setup-configuration as optional dependancy for mozilla-django-oidc-db to autoconfigure the Admin OIDC for our components 

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/mozilla-django-oidc-db#114]
Taiga OIP 2607

> Hey all, I saw that you added Admin-OIDC support via SetupConfig. It would be great if this can be part of the mozilla-django-oidc-db library as a contrib or optional dep, so we can use it in ALL our products.
> 
> Its about this piece of code: https://github.com/maykinmedia/open-inwoner/blob/ab1950d4f71ed85c1819dfcb69f027fba196c763/src/open_inwoner/configurations/bootstrap/auth.py#L198

So the idea is that we have a mozilla-django-oidc-db[setupconfig]  (see https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies ) which ensures django-setup-configuration is installed and that the above AdminOIDCConfigurationSettings bit from OIP is registered when using the setup-configuration management command

**Comment by sergei-maertens** [comment]
Feel free to take a look at https://github.com/maykinmedia/django-digid-eherkenning which has a similar setup with the optional `[oidc]` dependency group, especially with how tests are organized!

**Comment by sjoerdie** [comment]
I assigned it to Steven and Sidney. This item will now be processed by the PodiumD maykin team.

Sidney because I know he is already working on it in OIP also.

**Comment by sjoerdie** [comment]
Coner needs to finish this, it is blocking to add it to other components.

**Comment by joeribekker** [comment]
Blocked because @swrichards will introduce breaking changes to setup configuration.
