### ISSUE TITLE
oidc config: cannot leave 'groups claim' empty

### ISSUE THREAD

**Issue by sjoerdie** [maykinmedia/mozilla-django-oidc-db#63]
Setting groups claim will syn your groups with oidc provider.
Leaving the "groups claim" field empty should skip group sync. 

Leaving the groups claim empty is not possible in the openidconnectconfig form:

![image](https://user-images.githubusercontent.com/85243022/226357768-3dd5b271-bc1b-4f54-bd0f-529441bd936e.png)

Therefore authentications through oidc and authorization through local groups is not possible, because empty group claim is synced and clearing out all groups added through admin. 

Workaround:
```
In [1]: from mozilla_django_oidc_db.models import OpenIDConnectConfig
In [2]: oidc=OpenIDConnectConfig.objects.get()
In [4]: oidc.groups_claim=''
In [5]: oidc.save()
```

**Comment by joeribekker** [comment]
Fixed by #77
